# Generated by Django 6.0.4 on 2026-06-19 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('nombre_llamante', models.CharField(blank=True, max_length=120, verbose_name='nombre del llamante')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('emergencia', 'Emergencia'), ('denuncia', 'Denuncia'), ('seguimiento', 'Seguimiento'), ('otro', 'Otro')], default='consulta', max_length=20)),
                ('motivo', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('intervencion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('derivada', 'Derivada'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('requiere_seguimiento', models.BooleanField(default=False)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_llamadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'informe de llamada',
                'verbose_name_plural': 'informes de llamadas',
                'ordering': ['-fecha', '-hora', '-creado'],
            },
        ),
    ]
