# Generated by Django 6.0.4 on 2026-06-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llamadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.CharField(max_length=80, unique=True)),
                ('numero_origen', models.CharField(blank=True, max_length=60)),
                ('numero_destino', models.CharField(blank=True, max_length=60)),
                ('nombre_llamante', models.CharField(blank=True, max_length=120)),
                ('respondido_por', models.CharField(blank=True, max_length=80)),
                ('linea_origen', models.CharField(blank=True, max_length=80)),
                ('tipo_registro', models.CharField(blank=True, max_length=40)),
                ('estado', models.CharField(choices=[('ANSWERED', 'Contestada'), ('NO ANSWER', 'No contestada'), ('FAILED', 'Fallida'), ('BUSY', 'Ocupada')], max_length=20)),
                ('inicio', models.DateTimeField()),
                ('respondida', models.DateTimeField(blank=True, null=True)),
                ('finalizacion', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.PositiveIntegerField(default=0)),
                ('conversacion_segundos', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'registro de llamada',
                'verbose_name_plural': 'registros de llamadas',
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['inicio'], name='llamadas_re_inicio_670d8b_idx'), models.Index(fields=['estado'], name='llamadas_re_estado_03a9a7_idx'), models.Index(fields=['linea_origen'], name='llamadas_re_linea_o_4204d6_idx')],
            },
        ),
    ]
